[package]
name = "systole"
version.workspace = true
edition.workspace = true

[[bin]]
name = "systole"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
serde_json = { workspace = true }
systole-core = { path = "../systole-core" }
systole-rpg = { path = "../systole-rpg" }

[dev-dependencies]
tempfile = { workspace = true }
